USE InnovaParfumBD;
GO

-- 1. Eliminar la columna SALDO_PENDIENTE de VEN.VENTAS
IF EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'SALDO_PENDIENTE' AND Object_ID = Object_ID(N'VEN.VENTAS'))
BEGIN
    ALTER TABLE VEN.VENTAS DROP COLUMN SALDO_PENDIENTE;
END
GO

-- 2. Crear ADM.CLIENTES_CREDITO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ADM].[CLIENTES_CREDITO]') AND type in (N'U'))
BEGIN
    CREATE TABLE ADM.CLIENTES_CREDITO (
        ID_CLIENTE_CREDITO INT IDENTITY(1,1) PRIMARY KEY,
        ID_PERSONA INT NOT NULL,
        LIMITE_CREDITO DECIMAL(18,2) NOT NULL DEFAULT 0,
        SALDO_ACTUAL DECIMAL(18,2) NOT NULL DEFAULT 0,
        DIAS_CREDITO INT NOT NULL DEFAULT 30,
        ACTIVO BIT NOT NULL DEFAULT 1,
        FECHA_CREACION DATETIME NOT NULL DEFAULT SYSDATETIME(),
        CONSTRAINT FK_CLIENTES_CREDITO_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA)
    );
END
GO

-- 3. Crear VEN.CREDITOS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[VEN].[CREDITOS]') AND type in (N'U'))
BEGIN
    CREATE TABLE VEN.CREDITOS (
        ID_CREDITO INT IDENTITY(1,1) PRIMARY KEY,
        ID_VENTA INT NOT NULL,
        ID_PERSONA INT NOT NULL,
        MONTO_ORIGINAL DECIMAL(18,2) NOT NULL,
        SALDO_PENDIENTE DECIMAL(18,2) NOT NULL,
        FECHA_CREDITO DATE NOT NULL,
        FECHA_VENCIMIENTO DATE NOT NULL,
        ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO', -- ACTIVO, PAGADO, VENCIDO, ANULADO
        CONSTRAINT FK_CREDITOS_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VEN.VENTAS(ID_VENTA),
        CONSTRAINT FK_CREDITOS_PERSONA FOREIGN KEY (ID_PERSONA) REFERENCES ADM.PERSONAS(ID_PERSONA)
    );
END
GO

-- 4. Crear VEN.CREDITO_ABONOS
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[VEN].[CREDITO_ABONOS]') AND type in (N'U'))
BEGIN
    CREATE TABLE VEN.CREDITO_ABONOS (
        ID_ABONO INT IDENTITY(1,1) PRIMARY KEY,
        ID_CREDITO INT NOT NULL,
        MONTO DECIMAL(18,2) NOT NULL,
        FECHA DATETIME NOT NULL DEFAULT SYSDATETIME(),
        ID_METODO_PAGO INT NOT NULL,
        ID_USUARIO INT NOT NULL,
        OBSERVACION VARCHAR(200) NULL,
        CONSTRAINT FK_ABONOS_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES VEN.CREDITOS(ID_CREDITO),
        CONSTRAINT FK_ABONOS_METODO FOREIGN KEY (ID_METODO_PAGO) REFERENCES CAT.METODOS_PAGO(ID_METODO),
        CONSTRAINT FK_ABONOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES ADM.USUARIOS(ID_USUARIO)
    );
END
GO
