USE InnovaParfumBD;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[VEN].[VENTAS]') AND name = 'ID_TIPO_VENTA')
BEGIN
    ALTER TABLE [VEN].[VENTAS] ADD [ID_TIPO_VENTA] [int] NULL;
END
GO

UPDATE [VEN].[VENTAS] SET [ID_TIPO_VENTA] = 1 WHERE [ID_TIPO_VENTA] IS NULL;
GO

IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID(N'[VEN].[VENTA_DETALLE]') AND name = 'COSTO_UNITARIO_NIO')
BEGIN
    ALTER TABLE [VEN].[VENTA_DETALLE] ADD [COSTO_UNITARIO_NIO] [decimal](12,2) NULL;
END
GO

UPDATE vd
SET vd.[COSTO_UNITARIO_NIO] = ISNULL(p.COSTO_PRODUCTO, 0) + ISNULL(p.COSTO_ENVIO, 0)
FROM [VEN].[VENTA_DETALLE] vd
JOIN [INV].[PRODUCTOS] p ON vd.ID_PRODUCTO = p.ID_PRODUCTO
WHERE vd.[COSTO_UNITARIO_NIO] IS NULL;
GO
