ALTER VIEW CAJA.V_ESTADO_TURNO_ACTUAL AS
SELECT 
    T.*,
    U.USERNAME,
    (T.MONTO_INICIAL_BASE + T.TOTAL_EFECTIVO_BASE + ISNULL((SELECT SUM(MONTO) FROM CAJA.MOVIMIENTOS_VARIOS WHERE ID_TURNO = T.ID_TURNO AND ID_MONEDA = 1), 0)) AS SALDO_TEORICO_BASE,
    (T.MONTO_INICIAL_USD + T.TOTAL_EFECTIVO_USD + ISNULL((SELECT SUM(MONTO) FROM CAJA.MOVIMIENTOS_VARIOS WHERE ID_TURNO = T.ID_TURNO AND ID_MONEDA = 2), 0)) AS SALDO_TEORICO_USD
FROM CAJA.TURNOS T
JOIN ADM.USUARIOS U ON T.ID_USUARIO = U.ID_USUARIO
WHERE T.FECHA_CIERRE IS NULL;
