ALTER VIEW ADM.V_CLIENTE_DASHBOARD_STATS AS
SELECT 
    (SELECT COUNT(*) FROM ADM.PERSONAS WHERE ES_CLIENTE = 1 AND ID_ESTADO = 1) AS TotalClientes,
    (SELECT COUNT(*) FROM GAR.GARANTIAS WHERE ESTADO_GARANTIA = 'ACTIVA') AS TotalGarantiasActivas,
    (SELECT COUNT(DISTINCT ID_PERSONA) FROM VEN.VENTAS WHERE FECHA_VENTA >= DATEADD(DAY, -30, GETDATE())) AS ClientesConComprasRecientes,
    (SELECT COUNT(*) FROM VEN.CREDITOS WHERE ESTADO = 'ACTIVO') AS TotalCreditosActivos;
